### ISSUE TITLE
@conda-forge-admin, please add user @mbercx

### ISSUE THREAD

**Issue by mbercx** [conda-forge/aiida-vasp-feedstock#4]
### Comment:

@chrisjsewell could you make me a maintainer of this feedstock? 🙏 😘

**Comment by chrisjsewell** [comment]
Just make a PR (from a personal fork), adding your github handle to the maintainers list in the `recipe/meta.yaml` 😘

**Comment by chrisjsewell** [comment]
(and maybe have a look at doing it for all the others as well 😄  https://anaconda.org/search?q=aiida-)

**Comment by mbercx** [comment]
> (and maybe have a look at doing it for all the others as well 😄 https://anaconda.org/search?q=aiida-)

![hide-homer](https://github.com/conda-forge/aiida-vasp-feedstock/assets/25607960/573ddd04-e3df-4ced-88fc-a969265fd060)

**Comment by chrisjsewell** [comment]
![giphy](https://github.com/conda-forge/aiida-vasp-feedstock/assets/2997570/9f2e428c-e79a-4f91-88ce-efe65462f710)
